name: setup_library
description: A Flutter library for managing app themes, custom widgets, and shared utilities.


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

  # State Management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  # Networking
  dio: ^4.0.6

  # Storage & Preferences
  shared_preferences: ^2.0.15

  # UI & Icons
  hexcolor: ^3.0.1
  flutter_screenutil: ^5.9.0

  # Utilities
  device_preview: ^1.1.0
  loader_overlay: ^4.0.1
  conditional_builder_null_safety: ^0.0.6
  fluttertoast: ^8.2.4

  # Loading Animations
  loading_animation_widget: ^1.2.0+4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  # App Icon Generator
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: ""

# The following section is specific to Flutter packages.
flutter:
 uses-material-design: true


repository: https://github.com/rewannashat/setup_library.git
  
  

